version: "3.6"

services:
  ninthyard-php:
    image: elliotjreed/ninthyard-php
    container_name: ninthyard-php
    restart: always
    networks:
      - ninthyard
    volumes:
      - ./api/.env:/var/www/html/.env

  ninthyard-api-nginx:
    image: elliotjreed/ninthyard-api-nginx
    container_name: ninthyard-api-nginx
    restart: always
    networks:
      - ninthyard
      - web
    depends_on:
      - ninthyard-php
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:api.ninthyard.co.uk"
      - "traefik.protocol=h2c"
      - "traefik.port=89"

  ninthyard-nginx:
    image: elliotjreed/ninthyard-nginx
    container_name: ninthyard-nginx
    restart: always
    networks:
      - ninthyard
      - web
    depends_on:
      - ninthyard-php
      - ninthyard-api-nginx
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.www.frontend.rule=Host:www.ninthyard.co.uk"
      - "traefik.nonwww.frontend.rule=Host:ninthyard.co.uk"
      - "traefik.protocol=h2c"
      - "traefik.port=88"

networks:
  web:
    external: true
  ninthyard:
    name: ninthyard

