version: "3.6"

services:
  ninthyard-nginx:
    image: elliotjreed/ninthyard-nginx
    container_name: ninthyard-nginx
    restart: always
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.www.frontend.rule=Host:www.ninthyard.co.uk"
      - "traefik.nonwww.frontend.rule=Host:ninthyard.co.uk"
      - "traefik.protocol=h2c"
      - "traefik.port=90"

networks:
  web:
    external: true
